# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  #config.vm.synced_folder "./", "/vagrant"
  config.vm.provision "shell", path: "scripts/setup-arch.sh"
end
