# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.hostname = "master-controller"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provision "shell", path: "scripts/setup-arch.sh"
end
