# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "whonix" do |whonix|
    whonix.vm.box = "j7k6/whonix-gateway"
    whonix.vm.network :private_network, auto_config: false, virtualbox__intnet: "Whonix", adapter: 2
    whonix.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh", disabled: true
    whonix.vm.network :forwarded_port, guest: 22, host: 2219
    whonix.vm.synced_folder ".", "/vagrant", disabled: true
    whonix.ssh.username = "user"

    whonix.vm.provider "virtualbox" do |vb|
      vb.name = "whonix-gateway"
      vb.memory = 256
      vb.cpus = 1
    end
  end
end
