##########################
###Terraform Controller###
##########################
alias poweron-tc='sudo docker run -v /home/vagrant/.aws/credentials:/root/.aws/credentials:ro -v /vagrant/cloud/instances:/root/instances --name terraform_controller -d -h terraformController -p 2222:22 midockerdb/terraform-controller:0.1.2'
alias connect-tc='ssh -p 2222 root@localhost'
alias poweroff-tc='sudo docker stop terraform_controller && sudo docker rm terraform_controller'

#######################
###Packer Controller###
#######################
alias poweron-pc='sudo docker run -v /home/vagrant/.aws/credentials:/root/.aws/credentials:ro -v /vagrant/cloud/images:/root:ro --name packer_controller -h packerController -d -p 2223:22 midockerdb/packer-controller:0.1.2'
alias connect-pc='ssh -p 2223 root@localhost'
alias poweroff-pc='sudo docker stop packer_controller && sudo docker rm packer_controller'

#Generate SSH Key
alias generate-key='ssh-keygen -t ed25519 -f /vagrant/web-server/provisioner/images/tf-packer'

#Fetch terraform public_ip output from container
alias terraformipraw='sudo docker exec -it terraform_controller terraform output --state /root/instances/terraform.tfstate public_ip'
alias terraformip="terraformipraw | sed 's/\"//g'"  # Removes "" from output
