
source "qemu" "autogenerated_2" {
  accelerator      = "kvm"
  boot_wait        = "0s"
  communicator     = "winrm"
  cpus             = 2
  disk_size        = "${var.disk_size}"
  floppy_files     = ["${var.autounattend}", "../scripts/disable-screensaver.ps1", "../scripts/disable-winrm.ps1", "../scripts/enable-winrm.ps1", "../scripts/microsoft-updates.bat", "../scripts/unattend.xml", "../scripts/sysprep.bat", "../scripts/win-updates.ps1"]
  headless         = false
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  memory           = "${var.memory}"
  output_directory = "windows_2022-qemu"
  qemuargs         = [["-drive", "file=windows_2022-qemu/{{ .Name }},if=virtio,cache=writeback,discard=ignore,format=qcow2,index=1"], ["-drive", "file=${var.iso_url},media=cdrom,index=2"], ["-drive", "file=${var.virtio_win_iso},media=cdrom,index=3"]]
  shutdown_command = "a:/sysprep.bat"
  vm_name          = "WindowsServer2022"
  winrm_password   = "changeme"
  winrm_timeout    = "${var.winrm_timeout}"
  winrm_username   = "User"
}

build {
  sources = ["source.qemu.autogenerated_2"]

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    scripts         = ["../scripts/enable-rdp.bat"]
  }

  provisioner "powershell" {
    scripts = ["../scripts/vm-guest-tools.ps1", "../scripts/debloat-windows.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "${var.restart_timeout}"
  }

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    scripts         = ["../scripts/pin-powershell.bat", "../scripts/set-winrm-automatic.bat", "../scripts/uac-enable.bat", "../scripts/compile-dotnet-assemblies.bat", "../scripts/dis-updates.bat", "../scripts/compact.bat"]
  }
}
