# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora32"
  config.vm.hostname = "ipa-local-controller"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provision "shell", path: "scripts/setup-fedora.sh"
end
